import {
  adminCategoriesService,
  adminClientLogosService,
  adminContactSubmissionsService,
  adminFaqItemsService,
  adminHomepageSectionsService,
  adminMediaAssetsService,
  adminNavigationItemsService,
  adminNewsletterSubscribersService,
  adminPortfolioProjectsService,
  adminProductBlueprintsService,
  adminServicesService,
  adminSiteSettingsService,
  adminSocialLinksService,
  adminTestimonialsService,
  adminTranslationsService,
} from "../services/admin/adminResourceService";

export const adminResources = {
  services: {
    key: "services",
    route: "services",
    titleKey: "admin.resources.services.title",
    descriptionKey: "admin.resources.services.description",
    searchPlaceholderKey: "admin.resources.services.searchPlaceholder",
    service: adminServicesService,
    columns: [
      { key: "name", labelKey: "admin.columns.name" },
      { key: "slug", labelKey: "admin.columns.slug" },
      { key: "categoryName", labelKey: "admin.columns.category" },
      { key: "featured", labelKey: "admin.columns.featured", type: "boolean" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "name",
        labelKey: "admin.fields.name",
        type: "text",
        required: true,
      },
      { name: "slug", labelKey: "admin.fields.slug", type: "text" },
      {
        name: "shortDescription",
        labelKey: "admin.fields.shortDescription",
        type: "textarea",
        required: true,
      },
      {
        name: "fullDescription",
        labelKey: "admin.fields.fullDescription",
        type: "textarea",
      },
      { name: "categoryId", labelKey: "admin.fields.category", type: "number" },
      { name: "iconKey", labelKey: "admin.fields.iconKey", type: "text" },
      { name: "featured", labelKey: "admin.fields.featured", type: "checkbox" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  portfolioProjects: {
    key: "portfolioProjects",
    route: "portfolio-projects",
    titleKey: "admin.resources.portfolioProjects.title",
    descriptionKey: "admin.resources.portfolioProjects.description",
    searchPlaceholderKey: "admin.resources.portfolioProjects.searchPlaceholder",
    service: adminPortfolioProjectsService,
    columns: [
      { key: "title", labelKey: "admin.columns.title" },
      { key: "slug", labelKey: "admin.columns.slug" },
      { key: "projectType", labelKey: "admin.columns.type" },
      { key: "featured", labelKey: "admin.columns.featured", type: "boolean" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "title",
        labelKey: "admin.fields.title",
        type: "text",
        required: true,
      },
      { name: "slug", labelKey: "admin.fields.slug", type: "text" },
      {
        name: "summary",
        labelKey: "admin.fields.summary",
        type: "textarea",
        required: true,
      },
      {
        name: "description",
        labelKey: "admin.fields.description",
        type: "textarea",
      },
      {
        name: "clientIndustry",
        labelKey: "admin.fields.clientIndustry",
        type: "text",
      },
      {
        name: "projectType",
        labelKey: "admin.fields.projectType",
        type: "text",
      },
      {
        name: "coverImageUrl",
        labelKey: "admin.fields.coverImageUrl",
        type: "text",
      },
      { name: "liveUrl", labelKey: "admin.fields.liveUrl", type: "text" },
      { name: "featured", labelKey: "admin.fields.featured", type: "checkbox" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  productBlueprints: {
    key: "productBlueprints",
    route: "product-blueprints",
    titleKey: "admin.resources.productBlueprints.title",
    descriptionKey: "admin.resources.productBlueprints.description",
    searchPlaceholderKey: "admin.resources.productBlueprints.searchPlaceholder",
    service: adminProductBlueprintsService,
    columns: [
      { key: "title", labelKey: "admin.columns.title" },
      { key: "slug", labelKey: "admin.columns.slug" },
      { key: "featured", labelKey: "admin.columns.featured", type: "boolean" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "title",
        labelKey: "admin.fields.title",
        type: "text",
        required: true,
      },
      { name: "slug", labelKey: "admin.fields.slug", type: "text" },
      {
        name: "summary",
        labelKey: "admin.fields.summary",
        type: "textarea",
        required: true,
      },
      {
        name: "challengeStatement",
        labelKey: "admin.fields.challengeStatement",
        type: "textarea",
      },
      {
        name: "solutionOverview",
        labelKey: "admin.fields.solutionOverview",
        type: "textarea",
      },
      {
        name: "featureHighlights",
        labelKey: "admin.fields.featureHighlights",
        type: "textarea",
      },
      {
        name: "heroImageUrl",
        labelKey: "admin.fields.heroImageUrl",
        type: "text",
      },
      { name: "featured", labelKey: "admin.fields.featured", type: "checkbox" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  testimonials: {
    key: "testimonials",
    route: "testimonials",
    titleKey: "admin.resources.testimonials.title",
    descriptionKey: "admin.resources.testimonials.description",
    searchPlaceholderKey: "admin.resources.testimonials.searchPlaceholder",
    service: adminTestimonialsService,
    columns: [
      { key: "clientName", labelKey: "admin.columns.clientName" },
      { key: "organization", labelKey: "admin.columns.organization" },
      { key: "featured", labelKey: "admin.columns.featured", type: "boolean" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "clientName",
        labelKey: "admin.fields.clientName",
        type: "text",
        required: true,
      },
      { name: "clientRole", labelKey: "admin.fields.clientRole", type: "text" },
      {
        name: "organization",
        labelKey: "admin.fields.organization",
        type: "text",
      },
      {
        name: "quote",
        labelKey: "admin.fields.quote",
        type: "textarea",
        required: true,
      },
      { name: "avatarUrl", labelKey: "admin.fields.avatarUrl", type: "text" },
      { name: "featured", labelKey: "admin.fields.featured", type: "checkbox" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  clientLogos: {
    key: "clientLogos",
    route: "client-logos",
    titleKey: "admin.resources.clientLogos.title",
    descriptionKey: "admin.resources.clientLogos.description",
    searchPlaceholderKey: "admin.resources.clientLogos.searchPlaceholder",
    service: adminClientLogosService,
    columns: [
      { key: "name", labelKey: "admin.columns.name" },
      { key: "imageUrl", labelKey: "admin.columns.imageUrl" },
      { key: "featured", labelKey: "admin.columns.featured", type: "boolean" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "name",
        labelKey: "admin.fields.name",
        type: "text",
        required: true,
      },
      {
        name: "imageUrl",
        labelKey: "admin.fields.imageUrl",
        type: "text",
        required: true,
      },
      { name: "altText", labelKey: "admin.fields.altText", type: "text" },
      { name: "websiteUrl", labelKey: "admin.fields.websiteUrl", type: "text" },
      { name: "featured", labelKey: "admin.fields.featured", type: "checkbox" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  homepageSections: {
    key: "homepageSections",
    route: "homepage-sections",
    titleKey: "admin.resources.homepageSections.title",
    descriptionKey: "admin.resources.homepageSections.description",
    searchPlaceholderKey: "admin.resources.homepageSections.searchPlaceholder",
    service: adminHomepageSectionsService,
    columns: [
      { key: "title", labelKey: "admin.columns.title" },
      { key: "sectionKey", labelKey: "admin.columns.sectionKey" },
      { key: "placement", labelKey: "admin.columns.placement" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "sectionKey",
        labelKey: "admin.fields.sectionKey",
        type: "text",
        required: true,
      },
      { name: "placement", labelKey: "admin.fields.placement", type: "text" },
      { name: "eyebrow", labelKey: "admin.fields.eyebrow", type: "text" },
      {
        name: "title",
        labelKey: "admin.fields.title",
        type: "text",
        required: true,
      },
      { name: "subtitle", labelKey: "admin.fields.subtitle", type: "textarea" },
      { name: "body", labelKey: "admin.fields.body", type: "textarea" },
      { name: "imageUrl", labelKey: "admin.fields.imageUrl", type: "text" },
      {
        name: "ctaPrimaryLabel",
        labelKey: "admin.fields.ctaPrimaryLabel",
        type: "text",
      },
      {
        name: "ctaPrimaryUrl",
        labelKey: "admin.fields.ctaPrimaryUrl",
        type: "text",
      },
      {
        name: "ctaSecondaryLabel",
        labelKey: "admin.fields.ctaSecondaryLabel",
        type: "text",
      },
      {
        name: "ctaSecondaryUrl",
        labelKey: "admin.fields.ctaSecondaryUrl",
        type: "text",
      },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      { name: "featured", labelKey: "admin.fields.featured", type: "checkbox" },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  contactSubmissions: {
    key: "contactSubmissions",
    route: "contact-submissions",
    titleKey: "admin.resources.contactSubmissions.title",
    descriptionKey: "admin.resources.contactSubmissions.description",
    searchPlaceholderKey:
      "admin.resources.contactSubmissions.searchPlaceholder",
    service: adminContactSubmissionsService,
    createEnabled: false,
    columns: [
      { key: "fullName", labelKey: "admin.columns.fullName" },
      { key: "email", labelKey: "admin.columns.email" },
      { key: "subject", labelKey: "admin.columns.subject" },
      { key: "status", labelKey: "admin.columns.status" },
    ],
    fields: [
      {
        name: "fullName",
        labelKey: "admin.fields.fullName",
        type: "text",
        required: true,
      },
      {
        name: "email",
        labelKey: "admin.fields.email",
        type: "text",
        required: true,
      },
      {
        name: "phoneNumber",
        labelKey: "admin.fields.phoneNumber",
        type: "text",
      },
      {
        name: "companyName",
        labelKey: "admin.fields.companyName",
        type: "text",
      },
      { name: "subject", labelKey: "admin.fields.subject", type: "text" },
      { name: "message", labelKey: "admin.fields.message", type: "textarea" },
      { name: "status", labelKey: "admin.fields.status", type: "text" },
      {
        name: "preferredLanguage",
        labelKey: "admin.fields.preferredLanguage",
        type: "text",
      },
    ],
  },

  newsletterSubscribers: {
    key: "newsletterSubscribers",
    route: "newsletter-subscribers",
    titleKey: "admin.resources.newsletterSubscribers.title",
    descriptionKey: "admin.resources.newsletterSubscribers.description",
    searchPlaceholderKey:
      "admin.resources.newsletterSubscribers.searchPlaceholder",
    service: adminNewsletterSubscribersService,
    createEnabled: false,
    columns: [
      { key: "email", labelKey: "admin.columns.email" },
      { key: "active", labelKey: "admin.columns.active", type: "boolean" },
      { key: "language", labelKey: "admin.columns.language" },
    ],
    fields: [
      {
        name: "email",
        labelKey: "admin.fields.email",
        type: "text",
        required: true,
      },
      { name: "active", labelKey: "admin.fields.active", type: "checkbox" },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  translations: {
    key: "translations",
    route: "translations",
    titleKey: "admin.resources.translations.title",
    descriptionKey: "admin.resources.translations.description",
    searchPlaceholderKey: "admin.resources.translations.searchPlaceholder",
    service: adminTranslationsService,
    columns: [
      { key: "namespace", labelKey: "admin.columns.namespace" },
      { key: "translationKey", labelKey: "admin.columns.translationKey" },
      { key: "language", labelKey: "admin.columns.language" },
      { key: "value", labelKey: "admin.columns.value" },
    ],
    fields: [
      {
        name: "namespace",
        labelKey: "admin.fields.namespace",
        type: "text",
        required: true,
      },
      {
        name: "translationKey",
        labelKey: "admin.fields.translationKey",
        type: "text",
        required: true,
      },
      {
        name: "language",
        labelKey: "admin.fields.language",
        type: "text",
        required: true,
      },
      {
        name: "value",
        labelKey: "admin.fields.value",
        type: "textarea",
        required: true,
      },
    ],
  },

  siteSettings: {
    key: "siteSettings",
    route: "site-settings",
    titleKey: "admin.resources.siteSettings.title",
    descriptionKey: "admin.resources.siteSettings.description",
    searchPlaceholderKey: "admin.resources.siteSettings.searchPlaceholder",
    service: adminSiteSettingsService,
    columns: [
      { key: "groupName", labelKey: "admin.columns.group" },
      { key: "key", labelKey: "admin.columns.key" },
      { key: "value", labelKey: "admin.columns.value" },
      { key: "language", labelKey: "admin.columns.language" },
    ],
    fields: [
      { name: "groupName", labelKey: "admin.fields.groupName", type: "text" },
      {
        name: "key",
        labelKey: "admin.fields.key",
        type: "text",
        required: true,
      },
      {
        name: "value",
        labelKey: "admin.fields.value",
        type: "textarea",
        required: true,
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  navigationItems: {
    key: "navigationItems",
    route: "navigation-items",
    titleKey: "admin.resources.navigationItems.title",
    descriptionKey: "admin.resources.navigationItems.description",
    searchPlaceholderKey: "admin.resources.navigationItems.searchPlaceholder",
    service: adminNavigationItemsService,
    columns: [
      { key: "label", labelKey: "admin.columns.label" },
      { key: "url", labelKey: "admin.columns.url" },
      { key: "location", labelKey: "admin.columns.location" },
      { key: "visible", labelKey: "admin.columns.visible", type: "boolean" },
    ],
    fields: [
      {
        name: "label",
        labelKey: "admin.fields.label",
        type: "text",
        required: true,
      },
      {
        name: "url",
        labelKey: "admin.fields.url",
        type: "text",
        required: true,
      },
      { name: "location", labelKey: "admin.fields.location", type: "text" },
      { name: "target", labelKey: "admin.fields.target", type: "text" },
      { name: "visible", labelKey: "admin.fields.visible", type: "checkbox" },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  socialLinks: {
    key: "socialLinks",
    route: "social-links",
    titleKey: "admin.resources.socialLinks.title",
    descriptionKey: "admin.resources.socialLinks.description",
    searchPlaceholderKey: "admin.resources.socialLinks.searchPlaceholder",
    service: adminSocialLinksService,
    columns: [
      { key: "platform", labelKey: "admin.columns.platform" },
      { key: "url", labelKey: "admin.columns.url" },
      { key: "visible", labelKey: "admin.columns.visible", type: "boolean" },
    ],
    fields: [
      {
        name: "platform",
        labelKey: "admin.fields.platform",
        type: "text",
        required: true,
      },
      {
        name: "url",
        labelKey: "admin.fields.url",
        type: "text",
        required: true,
      },
      { name: "iconKey", labelKey: "admin.fields.iconKey", type: "text" },
      { name: "visible", labelKey: "admin.fields.visible", type: "checkbox" },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  mediaAssets: {
    key: "mediaAssets",
    route: "media-assets",
    titleKey: "admin.resources.mediaAssets.title",
    descriptionKey: "admin.resources.mediaAssets.description",
    searchPlaceholderKey: "admin.resources.mediaAssets.searchPlaceholder",
    service: adminMediaAssetsService,
    columns: [
      { key: "name", labelKey: "admin.columns.name" },
      { key: "assetType", labelKey: "admin.columns.assetType" },
      { key: "url", labelKey: "admin.columns.url" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "name",
        labelKey: "admin.fields.name",
        type: "text",
        required: true,
      },
      { name: "assetType", labelKey: "admin.fields.assetType", type: "text" },
      {
        name: "url",
        labelKey: "admin.fields.url",
        type: "text",
        required: true,
      },
      { name: "altText", labelKey: "admin.fields.altText", type: "text" },
      { name: "mimeType", labelKey: "admin.fields.mimeType", type: "text" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  faqs: {
    key: "faqs",
    route: "faqs",
    titleKey: "admin.resources.faqs.title",
    descriptionKey: "admin.resources.faqs.description",
    searchPlaceholderKey: "admin.resources.faqs.searchPlaceholder",
    service: adminFaqItemsService,
    columns: [
      { key: "question", labelKey: "admin.columns.question" },
      { key: "pageKey", labelKey: "admin.columns.pageKey" },
      {
        key: "published",
        labelKey: "admin.columns.published",
        type: "boolean",
      },
    ],
    fields: [
      {
        name: "question",
        labelKey: "admin.fields.question",
        type: "textarea",
        required: true,
      },
      {
        name: "answer",
        labelKey: "admin.fields.answer",
        type: "textarea",
        required: true,
      },
      { name: "pageKey", labelKey: "admin.fields.pageKey", type: "text" },
      { name: "categoryId", labelKey: "admin.fields.category", type: "number" },
      {
        name: "published",
        labelKey: "admin.fields.published",
        type: "checkbox",
      },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },

  categories: {
    key: "categories",
    route: "categories",
    titleKey: "admin.resources.categories.title",
    descriptionKey: "admin.resources.categories.description",
    searchPlaceholderKey: "admin.resources.categories.searchPlaceholder",
    service: adminCategoriesService,
    columns: [
      { key: "name", labelKey: "admin.columns.name" },
      { key: "slug", labelKey: "admin.columns.slug" },
      { key: "type", labelKey: "admin.columns.type" },
      { key: "visible", labelKey: "admin.columns.visible", type: "boolean" },
    ],
    fields: [
      {
        name: "name",
        labelKey: "admin.fields.name",
        type: "text",
        required: true,
      },
      { name: "slug", labelKey: "admin.fields.slug", type: "text" },
      { name: "type", labelKey: "admin.fields.type", type: "text" },
      {
        name: "description",
        labelKey: "admin.fields.description",
        type: "textarea",
      },
      { name: "visible", labelKey: "admin.fields.visible", type: "checkbox" },
      {
        name: "displayOrder",
        labelKey: "admin.fields.displayOrder",
        type: "number",
      },
      { name: "language", labelKey: "admin.fields.language", type: "text" },
    ],
  },
};

export const adminMenuItems = [
  { key: "dashboard", route: "/admin", labelKey: "admin.menu.dashboard" },
  {
    key: "services",
    route: "/admin/services",
    labelKey: "admin.menu.services",
  },
  {
    key: "portfolioProjects",
    route: "/admin/portfolio-projects",
    labelKey: "admin.menu.portfolioProjects",
  },
  {
    key: "productBlueprints",
    route: "/admin/product-blueprints",
    labelKey: "admin.menu.productBlueprints",
  },
  {
    key: "testimonials",
    route: "/admin/testimonials",
    labelKey: "admin.menu.testimonials",
  },
  {
    key: "clientLogos",
    route: "/admin/client-logos",
    labelKey: "admin.menu.clientLogos",
  },
  {
    key: "homepageSections",
    route: "/admin/homepage-sections",
    labelKey: "admin.menu.homepageSections",
  },
  {
    key: "contactSubmissions",
    route: "/admin/contact-submissions",
    labelKey: "admin.menu.contactSubmissions",
  },
  {
    key: "newsletterSubscribers",
    route: "/admin/newsletter-subscribers",
    labelKey: "admin.menu.newsletterSubscribers",
  },
  {
    key: "translations",
    route: "/admin/translations",
    labelKey: "admin.menu.translations",
  },
  {
    key: "siteSettings",
    route: "/admin/site-settings",
    labelKey: "admin.menu.siteSettings",
  },
  {
    key: "navigationItems",
    route: "/admin/navigation-items",
    labelKey: "admin.menu.navigationItems",
  },
  {
    key: "socialLinks",
    route: "/admin/social-links",
    labelKey: "admin.menu.socialLinks",
  },
  {
    key: "mediaAssets",
    route: "/admin/media-assets",
    labelKey: "admin.menu.mediaAssets",
  },
  { key: "faqs", route: "/admin/faqs", labelKey: "admin.menu.faqs" },
  {
    key: "categories",
    route: "/admin/categories",
    labelKey: "admin.menu.categories",
  },
];
