export const adminContentConfigs = {
  services: {
    endpoint: "/admin/services",
    title: "Services",
    eyebrow: "Content",
    description:
      "Create, update, publish, feature, order, and delete services.",
    nameField: "title",
    fields: [
      {
        name: "language",
        label: "Language",
        type: "select",
        options: ["EN", "HA", "IG", "YO"],
      },
      { name: "title", label: "Service Name", required: true },
      { name: "slug", label: "Slug", required: true },
      {
        name: "summary",
        label: "Short Description",
        type: "textarea",
        required: true,
      },
      { name: "description", label: "Full Description", type: "textarea" },
      { name: "category", label: "Category" },
      { name: "icon", label: "Icon Key" },
      { name: "imageUrl", label: "Image URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "sortOrder", label: "Display Order", type: "number" },
    ],
    initialValues: {
      language: "EN",
      title: "",
      slug: "",
      summary: "",
      description: "",
      category: "",
      icon: "",
      imageUrl: "",
      status: "DRAFT",
      featured: false,
      sortOrder: 0,
    },
  },

  clients: {
    endpoint: "/admin/client-logos",
    title: "Client Logos",
    eyebrow: "Trust",
    description: "Manage logos shown in client and trust sections.",
    nameField: "name",
    fields: [
      {
        name: "language",
        label: "Language",
        type: "select",
        options: ["EN", "HA", "IG", "YO"],
      },
      { name: "name", label: "Client Name", required: true },
      { name: "logoUrl", label: "Logo URL", required: true },
      { name: "websiteUrl", label: "Website URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "sortOrder", label: "Display Order", type: "number" },
    ],
    initialValues: {
      language: "EN",
      name: "",
      logoUrl: "",
      websiteUrl: "",
      status: "DRAFT",
      featured: false,
      sortOrder: 0,
    },
  },

  portfolio: {
    endpoint: "/admin/projects",
    title: "Portfolio Projects",
    eyebrow: "Work",
    description: "Manage case studies and portfolio projects.",
    nameField: "title",
    fields: [
      {
        name: "language",
        label: "Language",
        type: "select",
        options: ["EN", "HA", "IG", "YO"],
      },
      { name: "title", label: "Project Title", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "clientName", label: "Client Name" },
      { name: "projectUrl", label: "Project URL" },
      { name: "imageUrl", label: "Image URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "sortOrder", label: "Display Order", type: "number" },
    ],
    initialValues: {
      language: "EN",
      title: "",
      slug: "",
      summary: "",
      description: "",
      clientName: "",
      projectUrl: "",
      imageUrl: "",
      status: "DRAFT",
      featured: false,
      sortOrder: 0,
    },
  },

  products: {
    endpoint: "/admin/product-blueprints",
    title: "Product Blueprints",
    eyebrow: "Products",
    description: "Manage product blueprint pages.",
    nameField: "title",
    fields: [
      {
        name: "language",
        label: "Language",
        type: "select",
        options: ["EN", "HA", "IG", "YO"],
      },
      { name: "title", label: "Product Title", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "summary", label: "Summary", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "priceLabel", label: "Price Label" },
      { name: "imageUrl", label: "Image URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "sortOrder", label: "Display Order", type: "number" },
    ],
    initialValues: {
      language: "EN",
      title: "",
      slug: "",
      summary: "",
      description: "",
      priceLabel: "",
      imageUrl: "",
      status: "DRAFT",
      featured: false,
      sortOrder: 0,
    },
  },

  testimonials: {
    endpoint: "/admin/testimonials",
    title: "Testimonials",
    eyebrow: "Social Proof",
    description: "Manage testimonials and client feedback.",
    nameField: "clientName",
    fields: [
      {
        name: "language",
        label: "Language",
        type: "select",
        options: ["EN", "HA", "IG", "YO"],
      },
      { name: "clientName", label: "Client Name", required: true },
      { name: "clientRole", label: "Client Role" },
      { name: "companyName", label: "Company Name" },
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "avatarUrl", label: "Avatar URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "sortOrder", label: "Display Order", type: "number" },
    ],
    initialValues: {
      language: "EN",
      clientName: "",
      clientRole: "",
      companyName: "",
      quote: "",
      avatarUrl: "",
      status: "DRAFT",
      featured: false,
      sortOrder: 0,
    },
  },

  hero: {
    endpoint: "/admin/hero-sections",
    title: "Hero Sections",
    eyebrow: "Homepage",
    description: "Manage homepage and page hero sections.",
    nameField: "title",
    fields: [
      {
        name: "language",
        label: "Language",
        type: "select",
        options: ["EN", "HA", "IG", "YO"],
      },
      { name: "placement", label: "Placement", required: true },
      { name: "title", label: "Title", required: true },
      { name: "subtitle", label: "Subtitle" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "primaryButtonLabel", label: "Primary Button Label" },
      { name: "primaryButtonUrl", label: "Primary Button URL" },
      { name: "secondaryButtonLabel", label: "Secondary Button Label" },
      { name: "secondaryButtonUrl", label: "Secondary Button URL" },
      { name: "imageUrl", label: "Image URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["DRAFT", "PUBLISHED", "ARCHIVED"],
      },
      { name: "featured", label: "Featured", type: "checkbox" },
      { name: "sortOrder", label: "Display Order", type: "number" },
    ],
    initialValues: {
      language: "EN",
      placement: "HOME",
      title: "",
      subtitle: "",
      description: "",
      primaryButtonLabel: "Start a project",
      primaryButtonUrl: "/contact",
      secondaryButtonLabel: "View services",
      secondaryButtonUrl: "/services",
      imageUrl: "",
      status: "DRAFT",
      featured: false,
      sortOrder: 0,
    },
  },
};
